import "blockly/python";
export declare const SIGNAL_INVALID = -1;
export declare const SIGNAL_1BIT = 0;
export declare const SIGNAL_2BIT = 1;
export declare const SIGNAL_4BIT = 2;
export declare const SIGNAL_8BIT = 3;
export declare const SIGNAL_16BIT = 4;
export declare const SIGNAL_32BIT = 5;
export declare const SIGNAL_64BIT = 6;
export declare const COLOUR_ERROR = 0;
export declare const COLOUR_MODULE = 10;
export declare const COLOUR_LOGIC = 30;
export declare const COLOUR_INSTANTIATION = 90;
export declare const COLOUR_SPLITTER = 100;
export declare const COLOUR_CONCAT = 100;
export declare const COLOUR_1BIT = 250;
export declare const COLOUR_2BIT = 230;
export declare const COLOUR_4BIT = 210;
export declare const COLOUR_8BIT = 190;
export declare const COLOUR_16BIT = 170;
export declare const COLOUR_32BIT = 150;
export declare const COLOUR_64BIT = 130;
export declare const COLOUR_ASSIGN = 200;
export declare const COLOUR_BITS_SELECT = 200;
export declare const signalTypesDefinitions: {
    type: string;
    val: number;
    colour: number;
}[];
export declare const reservedTypes: string[];
export declare function getSignalBitLen(type: any): number;
export declare function getSignalColour(type: any): number;
export declare function isSameSignal(sig1: any, sig2: any): boolean;
export declare function get_temp_name(name: any): string;
export declare function setPrettySimMode(bool: any): void;
export declare function isPrettySimMode(): boolean;
